#!/usr/bin/env node
/**
 * Gera os manifestos do winget para uma versão do instalador Windows.
 *
 * Uso:
 *   node scripts/winget-bump.mjs --version 0.1.0 --exe ./dist/PrintBridge-Agent-0.1.0-setup.exe
 *   node scripts/winget-bump.mjs --version 0.1.0 --sha ABC123... [--owner X --repo Y]
 *
 * Depois: copiar ../winget/<version>/*.yaml para manifests/p/PrintBridge/Agent/<version>/
 * no fork de microsoft/winget-pkgs e abrir PR. O bot do winget valida o resto.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

export const PACKAGE_ID = "PrintBridge.Agent";
export const MANIFEST_VERSION = "1.10.0";

export function installerUrl(owner, repo, version) {
  return `https://github.com/${owner}/${repo}/releases/download/v${version}/PrintBridge-Agent-${version}-setup.exe`;
}

export function sha256File(filePath) {
  const hash = createHash("sha256");
  hash.update(fs.readFileSync(filePath));
  return hash.digest("hex").toUpperCase();
}

export function buildManifests({ version, url, sha, publisher = "PrintBridge" }) {
  const versionYaml = `# Automatically generated by scripts/winget-bump.mjs — do not edit by hand
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ${MANIFEST_VERSION}
`;
  const installerYaml = `# Automatically generated by scripts/winget-bump.mjs — do not edit by hand
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: ${url}
    InstallerSha256: ${sha}
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
ManifestType: installer
ManifestVersion: ${MANIFEST_VERSION}
`;
  const localeYaml = `# Automatically generated by scripts/winget-bump.mjs — do not edit by hand
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: ${publisher}
PackageName: PrintBridge Agent
License: Proprietary
ShortDescription: Agente de impressao local PrintBridge (fila duravel, tray, auto-update)
ManifestType: defaultLocale
ManifestVersion: ${MANIFEST_VERSION}
`;
  return {
    [`${PACKAGE_ID}.yaml`]: versionYaml,
    [`${PACKAGE_ID}.installer.yaml`]: installerYaml,
    [`${PACKAGE_ID}.locale.en-US.yaml`]: localeYaml,
  };
}

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : "";
}

// fileURLToPath: pathname cru vira "/C:/..." no Windows e nunca bate com argv.
const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const version = arg("--version");
  const owner = arg("--owner") || "bymarquin";
  const repo = arg("--repo") || "printbridge";
  const out = arg("--out") || path.join("..", "winget", version);
  if (!version) {
    console.error("Uso: winget-bump.mjs --version 0.1.0 (--exe ./dist/....exe | --sha ABC...) [--owner X --repo Y]");
    process.exit(2);
  }
  const exe = arg("--exe");
  const sha = arg("--sha") || (exe ? sha256File(exe) : "");
  if (!/^[0-9A-F]{64}$/.test(sha)) {
    console.error("SHA256 ausente/inválido — passe --exe ou --sha com 64 hex.");
    process.exit(2);
  }
  const files = buildManifests({ version, url: installerUrl(owner, repo, version), sha });
  fs.mkdirSync(out, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(out, name), content);
  }
  console.log(`winget/${version}/ atualizado (${Object.keys(files).length} arquivos)`);
  console.log("Proximo passo: copiar para manifests/p/PrintBridge/Agent/ no fork de microsoft/winget-pkgs e abrir PR.");
}
